### ISSUE TITLE
Issue with Image Quality

### ISSUE THREAD

**Issue by harsh21476** [JunHeum/BMBC#4]
Thank you for providing the code and models. I was trying to test out some 3fps footage which turns out to be noisy when converted to 12ps. Here are the Input and Output footage.

Input:
https://drive.google.com/file/d/1a7bJxVp9yGlh7Pe2nSO-NrxkrIF4WBPh/view?usp=sharing

Output:
https://drive.google.com/file/d/1A7jhqLodgqNDhgAnmWliIkR57uLJDevx/view?usp=sharing

I don't understand what's causing this.

**Comment by 972461099** [comment]
yes,I found that the video jitter is severe,especially the background。
and There are black edges on the edges of my test results。
![23](https://user-images.githubusercontent.com/23586956/98759256-aec02400-240b-11eb-95fb-c6154144bbe9.png)

**Comment by 972461099** [comment]
> yes,I found that the video jitter is severe,especially the background。
> and There are black edges on the edges of my test results。
> ![23](https://user-images.githubusercontent.com/23586956/98759256-aec02400-240b-11eb-95fb-c6154144bbe9.png)
i downgraded my pytorch to 1.3.1, the black edges is gone
