### ISSUE TITLE
Multi frame interpolation

### ISSUE THREAD

**Issue by tarun005** [JunHeum/BMBC#7]
HI,

How do we run the BMBC model for multi frame interpolation? run.py always seems to output one frame irrespective of the time_step parameter.

**Comment by JunHeum** [comment]
Hi,

For brevity, the run.py generates a single intermediate frame in time **t**.

It's a bit annoying, but the simplest way for multi-frame interpolation is to modify the configuration in the command and execute it multiple times.

This is the example for **x4** video interpolation.
```
    $ python run.py --first images/im1.png --second images/im3.png --output images/im2_025.png --time_step 0.25 
    $ python run.py --first images/im1.png --second images/im3.png --output images/im2_050.png --time_step 0.5 
    $ python run.py --first images/im1.png --second images/im3.png --output images/im2_075.png --time_step 0.75
```

**Comment by tarun005** [comment]
Thanks! Can you share pretrained models for multiframe interpolation?

**Comment by JunHeum** [comment]
Sure.

We use the same pre-trained model at any time_step parameter.

Hence, provided pre-trained model in README can be used for multi-frame interpolation.

For your convenience, I am attaching the corresponding part of the README.

Download [pre-trained model](https://drive.google.com/u/0/uc?export=download&confirm=JG-C&id=1YIxJguzgFp0t7iLHw1bKLrv7JQrc4lMG) parameters:
```
    $ unzip BMBC_Weights.zip
```
